name: Update Releases

on:
  schedule:
    - cron: "0 */3 * * *"   # 每3小时整点运行
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11

      - name: Restore data cache
        id: cache
        uses: actions/cache/restore@v3
        with:
          path: data
          key: data-cache-${{ github.run_id }}
          restore-keys: |
            data-cache-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run crawler
        env:
          BOTTOKEN: ${{ secrets.BOTTOKEN }}
          CHATID: ${{ secrets.CHATID }}
        run: python main.py

      - name: Save data cache
        uses: actions/cache/save@v3
        with:
          path: data
          key: data-cache-${{ github.run_id }}
